project:
  type: website

website:
  title: "Sample Size Calculation"
  navbar:
    left:
      - href: index.qmd
      - ref.qmd
      - about.qmd

format:
  html:
   theme:
    light: flatly
    dark: darkly
    css: styles.css
    toc: true

editor: visual

