project:
  type: website

website:
  favicon: figures/myfav.png
  page-navigation: true
  title: "Sample Size Calculation"
  navbar:
    left:
      - href: index.qmd
      - ref.qmd
      - text: "Slides"
        menu:
          - Sample_Size_GHRU.qmd
      - openepi.qmd
      - about.qmd
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    
editor: visual


